//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPL.WEB.EXTRA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectionSet", Namespace="http://schemas.datacontract.org/2004/07/EX.Projection.Model")]
    [System.SerializableAttribute()]
    public partial class ProjectionSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl14Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dbl9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblToAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW14Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblW9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intColField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intSerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAMFMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMerzeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMonthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMpoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProjectionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProjectionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProjectionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strZoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl1 {
            get {
                return this.dbl1Field;
            }
            set {
                if ((this.dbl1Field.Equals(value) != true)) {
                    this.dbl1Field = value;
                    this.RaisePropertyChanged("dbl1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl10 {
            get {
                return this.dbl10Field;
            }
            set {
                if ((this.dbl10Field.Equals(value) != true)) {
                    this.dbl10Field = value;
                    this.RaisePropertyChanged("dbl10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl11 {
            get {
                return this.dbl11Field;
            }
            set {
                if ((this.dbl11Field.Equals(value) != true)) {
                    this.dbl11Field = value;
                    this.RaisePropertyChanged("dbl11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl12 {
            get {
                return this.dbl12Field;
            }
            set {
                if ((this.dbl12Field.Equals(value) != true)) {
                    this.dbl12Field = value;
                    this.RaisePropertyChanged("dbl12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl13 {
            get {
                return this.dbl13Field;
            }
            set {
                if ((this.dbl13Field.Equals(value) != true)) {
                    this.dbl13Field = value;
                    this.RaisePropertyChanged("dbl13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl14 {
            get {
                return this.dbl14Field;
            }
            set {
                if ((this.dbl14Field.Equals(value) != true)) {
                    this.dbl14Field = value;
                    this.RaisePropertyChanged("dbl14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl15 {
            get {
                return this.dbl15Field;
            }
            set {
                if ((this.dbl15Field.Equals(value) != true)) {
                    this.dbl15Field = value;
                    this.RaisePropertyChanged("dbl15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl2 {
            get {
                return this.dbl2Field;
            }
            set {
                if ((this.dbl2Field.Equals(value) != true)) {
                    this.dbl2Field = value;
                    this.RaisePropertyChanged("dbl2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl3 {
            get {
                return this.dbl3Field;
            }
            set {
                if ((this.dbl3Field.Equals(value) != true)) {
                    this.dbl3Field = value;
                    this.RaisePropertyChanged("dbl3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl4 {
            get {
                return this.dbl4Field;
            }
            set {
                if ((this.dbl4Field.Equals(value) != true)) {
                    this.dbl4Field = value;
                    this.RaisePropertyChanged("dbl4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl5 {
            get {
                return this.dbl5Field;
            }
            set {
                if ((this.dbl5Field.Equals(value) != true)) {
                    this.dbl5Field = value;
                    this.RaisePropertyChanged("dbl5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl6 {
            get {
                return this.dbl6Field;
            }
            set {
                if ((this.dbl6Field.Equals(value) != true)) {
                    this.dbl6Field = value;
                    this.RaisePropertyChanged("dbl6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl7 {
            get {
                return this.dbl7Field;
            }
            set {
                if ((this.dbl7Field.Equals(value) != true)) {
                    this.dbl7Field = value;
                    this.RaisePropertyChanged("dbl7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl8 {
            get {
                return this.dbl8Field;
            }
            set {
                if ((this.dbl8Field.Equals(value) != true)) {
                    this.dbl8Field = value;
                    this.RaisePropertyChanged("dbl8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dbl9 {
            get {
                return this.dbl9Field;
            }
            set {
                if ((this.dbl9Field.Equals(value) != true)) {
                    this.dbl9Field = value;
                    this.RaisePropertyChanged("dbl9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblToAmt {
            get {
                return this.dblToAmtField;
            }
            set {
                if ((this.dblToAmtField.Equals(value) != true)) {
                    this.dblToAmtField = value;
                    this.RaisePropertyChanged("dblToAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW1 {
            get {
                return this.dblW1Field;
            }
            set {
                if ((this.dblW1Field.Equals(value) != true)) {
                    this.dblW1Field = value;
                    this.RaisePropertyChanged("dblW1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW10 {
            get {
                return this.dblW10Field;
            }
            set {
                if ((this.dblW10Field.Equals(value) != true)) {
                    this.dblW10Field = value;
                    this.RaisePropertyChanged("dblW10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW11 {
            get {
                return this.dblW11Field;
            }
            set {
                if ((this.dblW11Field.Equals(value) != true)) {
                    this.dblW11Field = value;
                    this.RaisePropertyChanged("dblW11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW12 {
            get {
                return this.dblW12Field;
            }
            set {
                if ((this.dblW12Field.Equals(value) != true)) {
                    this.dblW12Field = value;
                    this.RaisePropertyChanged("dblW12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW13 {
            get {
                return this.dblW13Field;
            }
            set {
                if ((this.dblW13Field.Equals(value) != true)) {
                    this.dblW13Field = value;
                    this.RaisePropertyChanged("dblW13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW14 {
            get {
                return this.dblW14Field;
            }
            set {
                if ((this.dblW14Field.Equals(value) != true)) {
                    this.dblW14Field = value;
                    this.RaisePropertyChanged("dblW14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW15 {
            get {
                return this.dblW15Field;
            }
            set {
                if ((this.dblW15Field.Equals(value) != true)) {
                    this.dblW15Field = value;
                    this.RaisePropertyChanged("dblW15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW2 {
            get {
                return this.dblW2Field;
            }
            set {
                if ((this.dblW2Field.Equals(value) != true)) {
                    this.dblW2Field = value;
                    this.RaisePropertyChanged("dblW2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW3 {
            get {
                return this.dblW3Field;
            }
            set {
                if ((this.dblW3Field.Equals(value) != true)) {
                    this.dblW3Field = value;
                    this.RaisePropertyChanged("dblW3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW4 {
            get {
                return this.dblW4Field;
            }
            set {
                if ((this.dblW4Field.Equals(value) != true)) {
                    this.dblW4Field = value;
                    this.RaisePropertyChanged("dblW4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW5 {
            get {
                return this.dblW5Field;
            }
            set {
                if ((this.dblW5Field.Equals(value) != true)) {
                    this.dblW5Field = value;
                    this.RaisePropertyChanged("dblW5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW6 {
            get {
                return this.dblW6Field;
            }
            set {
                if ((this.dblW6Field.Equals(value) != true)) {
                    this.dblW6Field = value;
                    this.RaisePropertyChanged("dblW6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW7 {
            get {
                return this.dblW7Field;
            }
            set {
                if ((this.dblW7Field.Equals(value) != true)) {
                    this.dblW7Field = value;
                    this.RaisePropertyChanged("dblW7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW8 {
            get {
                return this.dblW8Field;
            }
            set {
                if ((this.dblW8Field.Equals(value) != true)) {
                    this.dblW8Field = value;
                    this.RaisePropertyChanged("dblW8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblW9 {
            get {
                return this.dblW9Field;
            }
            set {
                if ((this.dblW9Field.Equals(value) != true)) {
                    this.dblW9Field = value;
                    this.RaisePropertyChanged("dblW9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intCol {
            get {
                return this.intColField;
            }
            set {
                if ((this.intColField.Equals(value) != true)) {
                    this.intColField = value;
                    this.RaisePropertyChanged("intCol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intRow {
            get {
                return this.intRowField;
            }
            set {
                if ((this.intRowField.Equals(value) != true)) {
                    this.intRowField = value;
                    this.RaisePropertyChanged("intRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intSerial {
            get {
                return this.intSerialField;
            }
            set {
                if ((this.intSerialField.Equals(value) != true)) {
                    this.intSerialField = value;
                    this.RaisePropertyChanged("intSerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intStatus {
            get {
                return this.intStatusField;
            }
            set {
                if ((this.intStatusField.Equals(value) != true)) {
                    this.intStatusField = value;
                    this.RaisePropertyChanged("intStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strAMFM {
            get {
                return this.strAMFMField;
            }
            set {
                if ((object.ReferenceEquals(this.strAMFMField, value) != true)) {
                    this.strAMFMField = value;
                    this.RaisePropertyChanged("strAMFM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDivision {
            get {
                return this.strDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.strDivisionField, value) != true)) {
                    this.strDivisionField = value;
                    this.RaisePropertyChanged("strDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strEndDate {
            get {
                return this.strEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strEndDateField, value) != true)) {
                    this.strEndDateField = value;
                    this.RaisePropertyChanged("strEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMerzeName {
            get {
                return this.strMerzeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strMerzeNameField, value) != true)) {
                    this.strMerzeNameField = value;
                    this.RaisePropertyChanged("strMerzeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMonthID {
            get {
                return this.strMonthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.strMonthIDField, value) != true)) {
                    this.strMonthIDField = value;
                    this.RaisePropertyChanged("strMonthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMpoName {
            get {
                return this.strMpoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strMpoNameField, value) != true)) {
                    this.strMpoNameField = value;
                    this.RaisePropertyChanged("strMpoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProjectionDate {
            get {
                return this.strProjectionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strProjectionDateField, value) != true)) {
                    this.strProjectionDateField = value;
                    this.RaisePropertyChanged("strProjectionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProjectionKey {
            get {
                return this.strProjectionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.strProjectionKeyField, value) != true)) {
                    this.strProjectionKeyField = value;
                    this.RaisePropertyChanged("strProjectionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProjectionName {
            get {
                return this.strProjectionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strProjectionNameField, value) != true)) {
                    this.strProjectionNameField = value;
                    this.RaisePropertyChanged("strProjectionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strStartDate {
            get {
                return this.strStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strStartDateField, value) != true)) {
                    this.strStartDateField = value;
                    this.RaisePropertyChanged("strStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strZone {
            get {
                return this.strZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.strZoneField, value) != true)) {
                    this.strZoneField = value;
                    this.RaisePropertyChanged("strZone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mprojection", Namespace="http://schemas.datacontract.org/2004/07/EX.Projection.Model")]
    [System.SerializableAttribute()]
    public partial class Mprojection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double APRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AUGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DECField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FRBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double JANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double JULField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double JUNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MAYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NOVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OCTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblTotalPerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblUp_toDate_amntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strGRNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strLedgerNameMerzeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strParticularsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strZoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double APR {
            get {
                return this.APRField;
            }
            set {
                if ((this.APRField.Equals(value) != true)) {
                    this.APRField = value;
                    this.RaisePropertyChanged("APR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AUG {
            get {
                return this.AUGField;
            }
            set {
                if ((this.AUGField.Equals(value) != true)) {
                    this.AUGField = value;
                    this.RaisePropertyChanged("AUG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DEC {
            get {
                return this.DECField;
            }
            set {
                if ((this.DECField.Equals(value) != true)) {
                    this.DECField = value;
                    this.RaisePropertyChanged("DEC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FRB {
            get {
                return this.FRBField;
            }
            set {
                if ((this.FRBField.Equals(value) != true)) {
                    this.FRBField = value;
                    this.RaisePropertyChanged("FRB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double JAN {
            get {
                return this.JANField;
            }
            set {
                if ((this.JANField.Equals(value) != true)) {
                    this.JANField = value;
                    this.RaisePropertyChanged("JAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double JUL {
            get {
                return this.JULField;
            }
            set {
                if ((this.JULField.Equals(value) != true)) {
                    this.JULField = value;
                    this.RaisePropertyChanged("JUL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double JUN {
            get {
                return this.JUNField;
            }
            set {
                if ((this.JUNField.Equals(value) != true)) {
                    this.JUNField = value;
                    this.RaisePropertyChanged("JUN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MAR {
            get {
                return this.MARField;
            }
            set {
                if ((this.MARField.Equals(value) != true)) {
                    this.MARField = value;
                    this.RaisePropertyChanged("MAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MAY {
            get {
                return this.MAYField;
            }
            set {
                if ((this.MAYField.Equals(value) != true)) {
                    this.MAYField = value;
                    this.RaisePropertyChanged("MAY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NOV {
            get {
                return this.NOVField;
            }
            set {
                if ((this.NOVField.Equals(value) != true)) {
                    this.NOVField = value;
                    this.RaisePropertyChanged("NOV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OCT {
            get {
                return this.OCTField;
            }
            set {
                if ((this.OCTField.Equals(value) != true)) {
                    this.OCTField = value;
                    this.RaisePropertyChanged("OCT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SEP {
            get {
                return this.SEPField;
            }
            set {
                if ((this.SEPField.Equals(value) != true)) {
                    this.SEPField = value;
                    this.RaisePropertyChanged("SEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblBalance {
            get {
                return this.dblBalanceField;
            }
            set {
                if ((this.dblBalanceField.Equals(value) != true)) {
                    this.dblBalanceField = value;
                    this.RaisePropertyChanged("dblBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblTotalPer {
            get {
                return this.dblTotalPerField;
            }
            set {
                if ((this.dblTotalPerField.Equals(value) != true)) {
                    this.dblTotalPerField = value;
                    this.RaisePropertyChanged("dblTotalPer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblUp_toDate_amnt {
            get {
                return this.dblUp_toDate_amntField;
            }
            set {
                if ((this.dblUp_toDate_amntField.Equals(value) != true)) {
                    this.dblUp_toDate_amntField = value;
                    this.RaisePropertyChanged("dblUp_toDate_amnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intMode {
            get {
                return this.intModeField;
            }
            set {
                if ((this.intModeField.Equals(value) != true)) {
                    this.intModeField = value;
                    this.RaisePropertyChanged("intMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intid {
            get {
                return this.intidField;
            }
            set {
                if ((this.intidField.Equals(value) != true)) {
                    this.intidField = value;
                    this.RaisePropertyChanged("intid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strArea {
            get {
                return this.strAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.strAreaField, value) != true)) {
                    this.strAreaField = value;
                    this.RaisePropertyChanged("strArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDivision {
            get {
                return this.strDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.strDivisionField, value) != true)) {
                    this.strDivisionField = value;
                    this.RaisePropertyChanged("strDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strGRName {
            get {
                return this.strGRNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strGRNameField, value) != true)) {
                    this.strGRNameField = value;
                    this.RaisePropertyChanged("strGRName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strLedgerNameMerze {
            get {
                return this.strLedgerNameMerzeField;
            }
            set {
                if ((object.ReferenceEquals(this.strLedgerNameMerzeField, value) != true)) {
                    this.strLedgerNameMerzeField = value;
                    this.RaisePropertyChanged("strLedgerNameMerze");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strParticulars {
            get {
                return this.strParticularsField;
            }
            set {
                if ((object.ReferenceEquals(this.strParticularsField, value) != true)) {
                    this.strParticularsField = value;
                    this.RaisePropertyChanged("strParticulars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strZone {
            get {
                return this.strZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.strZoneField, value) != true)) {
                    this.strZoneField = value;
                    this.RaisePropertyChanged("strZone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectonMonthConfig", Namespace="http://schemas.datacontract.org/2004/07/EX.Projection.Model")]
    [System.SerializableAttribute()]
    public partial class ProjectonMonthConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intSerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long lngTotalAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long lngTotalLedgerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strFromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strGRNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMonthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strToDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strZoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intSerial {
            get {
                return this.intSerialField;
            }
            set {
                if ((this.intSerialField.Equals(value) != true)) {
                    this.intSerialField = value;
                    this.RaisePropertyChanged("intSerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intStatus {
            get {
                return this.intStatusField;
            }
            set {
                if ((this.intStatusField.Equals(value) != true)) {
                    this.intStatusField = value;
                    this.RaisePropertyChanged("intStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lngTotalArea {
            get {
                return this.lngTotalAreaField;
            }
            set {
                if ((this.lngTotalAreaField.Equals(value) != true)) {
                    this.lngTotalAreaField = value;
                    this.RaisePropertyChanged("lngTotalArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lngTotalLedger {
            get {
                return this.lngTotalLedgerField;
            }
            set {
                if ((this.lngTotalLedgerField.Equals(value) != true)) {
                    this.lngTotalLedgerField = value;
                    this.RaisePropertyChanged("lngTotalLedger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strArea {
            get {
                return this.strAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.strAreaField, value) != true)) {
                    this.strAreaField = value;
                    this.RaisePropertyChanged("strArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDivision {
            get {
                return this.strDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.strDivisionField, value) != true)) {
                    this.strDivisionField = value;
                    this.RaisePropertyChanged("strDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strFromDate {
            get {
                return this.strFromDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strFromDateField, value) != true)) {
                    this.strFromDateField = value;
                    this.RaisePropertyChanged("strFromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strGRName {
            get {
                return this.strGRNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strGRNameField, value) != true)) {
                    this.strGRNameField = value;
                    this.RaisePropertyChanged("strGRName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMonthID {
            get {
                return this.strMonthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.strMonthIDField, value) != true)) {
                    this.strMonthIDField = value;
                    this.RaisePropertyChanged("strMonthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strStatus {
            get {
                return this.strStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.strStatusField, value) != true)) {
                    this.strStatusField = value;
                    this.RaisePropertyChanged("strStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strToDate {
            get {
                return this.strToDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strToDateField, value) != true)) {
                    this.strToDateField = value;
                    this.RaisePropertyChanged("strToDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strZone {
            get {
                return this.strZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.strZoneField, value) != true)) {
                    this.strZoneField = value;
                    this.RaisePropertyChanged("strZone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PCollectionCopmarison", Namespace="http://schemas.datacontract.org/2004/07/EX.Projection.Model")]
    [System.SerializableAttribute()]
    public partial class PCollectionCopmarison : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dblAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strLastMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strLedgerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMonthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double strMonthNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMonthNameeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProjectionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strstrDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dblAmount {
            get {
                return this.dblAmountField;
            }
            set {
                if ((this.dblAmountField.Equals(value) != true)) {
                    this.dblAmountField = value;
                    this.RaisePropertyChanged("dblAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strArea {
            get {
                return this.strAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.strAreaField, value) != true)) {
                    this.strAreaField = value;
                    this.RaisePropertyChanged("strArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strDivision {
            get {
                return this.strDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.strDivisionField, value) != true)) {
                    this.strDivisionField = value;
                    this.RaisePropertyChanged("strDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strEndDate {
            get {
                return this.strEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strEndDateField, value) != true)) {
                    this.strEndDateField = value;
                    this.RaisePropertyChanged("strEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strLastMonth {
            get {
                return this.strLastMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.strLastMonthField, value) != true)) {
                    this.strLastMonthField = value;
                    this.RaisePropertyChanged("strLastMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strLedgerName {
            get {
                return this.strLedgerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strLedgerNameField, value) != true)) {
                    this.strLedgerNameField = value;
                    this.RaisePropertyChanged("strLedgerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMonthID {
            get {
                return this.strMonthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.strMonthIDField, value) != true)) {
                    this.strMonthIDField = value;
                    this.RaisePropertyChanged("strMonthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double strMonthName {
            get {
                return this.strMonthNameField;
            }
            set {
                if ((this.strMonthNameField.Equals(value) != true)) {
                    this.strMonthNameField = value;
                    this.RaisePropertyChanged("strMonthName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMonthNamee {
            get {
                return this.strMonthNameeField;
            }
            set {
                if ((object.ReferenceEquals(this.strMonthNameeField, value) != true)) {
                    this.strMonthNameeField = value;
                    this.RaisePropertyChanged("strMonthNamee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProjectionName {
            get {
                return this.strProjectionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.strProjectionNameField, value) != true)) {
                    this.strProjectionNameField = value;
                    this.RaisePropertyChanged("strProjectionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strZone {
            get {
                return this.strZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.strZoneField, value) != true)) {
                    this.strZoneField = value;
                    this.RaisePropertyChanged("strZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strstrDate {
            get {
                return this.strstrDateField;
            }
            set {
                if ((object.ReferenceEquals(this.strstrDateField, value) != true)) {
                    this.strstrDateField = value;
                    this.RaisePropertyChanged("strstrDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EXTRA.ISWPRJ")]
    public interface ISWPRJ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayWeeklyProjectionchild", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayWeeklyProjectionchildResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayWeeklyProjectionchild(string strDeComID, string strMonthID, string strKey, string strLedgerName, string strProjection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayMonthlyProjectionchild", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayMonthlyProjectionchildResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayMonthlyProjectionchild(string strDeComID, string strMonthID, string strKey, string strLedgerName, string strProjection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetDivisionFromZone", ReplyAction="http://tempuri.org/ISWPRJ/mGetDivisionFromZoneResponse")]
        DPL.WEB.EXTRA.Mprojection[] mGetDivisionFromZone(string strDeComID, string strZone, int intHalt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mDeletePerformanve", ReplyAction="http://tempuri.org/ISWPRJ/mDeletePerformanveResponse")]
        string mDeletePerformanve(string strcomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mrptFillDisplayMonthlyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mrptFillDisplayMonthlyProjectionResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mrptFillDisplayMonthlyProjection(string strDeComID, string strMonthID, string strDivision, int intmode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillWeeklyProjectionReport", ReplyAction="http://tempuri.org/ISWPRJ/mFillWeeklyProjectionReportResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillWeeklyProjectionReport(string strDeComID, string strMonthID, string strDivision, int intmode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionValue", ReplyAction="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionValueResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillMonthlyProjectionValue(string strDeComID, string strMonthID, string strLedgerName, string strProjectionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayLedgerNameWeeklyReport", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayLedgerNameWeeklyReportResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayLedgerNameWeeklyReport(string strDeComID, string strKey, string strDivision, int Intmode, string vstrUserName, string strZone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillWeeklyProjectionList", ReplyAction="http://tempuri.org/ISWPRJ/mFillWeeklyProjectionListResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillWeeklyProjectionList(string strDeComID, string VstruserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mDeleteWeeklyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mDeleteWeeklyProjectionResponse")]
        string mDeleteWeeklyProjection(string strDeComID, string strMonthID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayWeeklyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayWeeklyProjectionResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayWeeklyProjection(string strDeComID, string strMonthID, string strDivision, string strMPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayLedgerNameWeekly", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayLedgerNameWeeklyResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayLedgerNameWeekly(string strDeComID, string strKey, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mInsertWeeklyProjectionSet", ReplyAction="http://tempuri.org/ISWPRJ/mInsertWeeklyProjectionSetResponse")]
        string mInsertWeeklyProjectionSet(string strDeComID, string strKey, string strMonthID, string strDivision, string strBranchID, string strLedgerName, string strHeadName, double dblAmount, double dblWrittenAmount, int intDel, int intCols, int intRow, string strCommProjectionName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/getZoneFromDivsion", ReplyAction="http://tempuri.org/ISWPRJ/getZoneFromDivsionResponse")]
        DPL.WEB.EXTRA.ProjectonMonthConfig[] getZoneFromDivsion(string strDeComID, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mInsertMpoPerformance", ReplyAction="http://tempuri.org/ISWPRJ/mInsertMpoPerformanceResponse")]
        string mInsertMpoPerformance(string strDeComID, string strLedgerName, string strFdate, string strTdate, int intmode, int intSelection, int intbaseTarget, string strSelectionID, int intStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mQueryPerformance", ReplyAction="http://tempuri.org/ISWPRJ/mQueryPerformanceResponse")]
        DPL.WEB.EXTRA.Mprojection[] mQueryPerformance(string strDeComID, int intMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetLedgerGroupLoad", ReplyAction="http://tempuri.org/ISWPRJ/mGetLedgerGroupLoadResponse")]
        DPL.WEB.EXTRA.Mprojection[] mGetLedgerGroupLoad(string strDeComID, int intMode, string struserName, int intstatus, string strBranchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mInsertMonthConfig", ReplyAction="http://tempuri.org/ISWPRJ/mInsertMonthConfigResponse")]
        string mInsertMonthConfig(string strDeComID, string strMonthID, string strMonthFromDate, string strMonthToDate, int intStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillMonthConfig", ReplyAction="http://tempuri.org/ISWPRJ/mFillMonthConfigResponse")]
        DPL.WEB.EXTRA.ProjectonMonthConfig[] mFillMonthConfig(string strDeComID, int intStaus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/DeletetMonthConfig", ReplyAction="http://tempuri.org/ISWPRJ/DeletetMonthConfigResponse")]
        string DeletetMonthConfig(string strDeComID, int intSerialkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mUpdateMonthConfigpublic", ReplyAction="http://tempuri.org/ISWPRJ/mUpdateMonthConfigpublicResponse")]
        string mUpdateMonthConfigpublic(string strDeComID, string strMonthID, string strFromDate, string strToDate, int intStatus, int intSerialKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mInsertProjectionSetup", ReplyAction="http://tempuri.org/ISWPRJ/mInsertProjectionSetupResponse")]
        string mInsertProjectionSetup(string strDeComID, string strMonthID, string DgGrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillPojictionConfig", ReplyAction="http://tempuri.org/ISWPRJ/mFillPojictionConfigResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillPojictionConfig(string strDeComID, string strMonthID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/DeletetProjectionSetUp", ReplyAction="http://tempuri.org/ISWPRJ/DeletetProjectionSetUpResponse")]
        string DeletetProjectionSetUp(string strDeComID, string strProjectionkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mUpdateProjectionSetup", ReplyAction="http://tempuri.org/ISWPRJ/mUpdateProjectionSetupResponse")]
        string mUpdateProjectionSetup(string strDeComID, string strMonthID, string DgGrid, string strProjectionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillMonthlyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillMonthlyProjection(string strDeComID, string strProjectionMonth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionLedger", ReplyAction="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionLedgerResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillMonthlyProjectionLedger(string strDeComID, string strLedgerGroup, string strMonthID, int intmode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mInsertMonthlyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mInsertMonthlyProjectionResponse")]
        string mInsertMonthlyProjection(string strDeComID, string strKey, string strMonthID, string strDivision, string strBranchID, string strLedgerName, string strHeadName, double dblAmount, int intDel, int intCols, int intRow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionList", ReplyAction="http://tempuri.org/ISWPRJ/mFillMonthlyProjectionListResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillMonthlyProjectionList(string strDeComID, string VstruserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayMonthlyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayMonthlyProjectionResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayMonthlyProjection(string strDeComID, string strMonthID, string strDivision, string strprojectionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mFillDisplayLedgerName", ReplyAction="http://tempuri.org/ISWPRJ/mFillDisplayLedgerNameResponse")]
        DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayLedgerName(string strDeComID, string strKey, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mDeleteMonthlyProjection", ReplyAction="http://tempuri.org/ISWPRJ/mDeleteMonthlyProjectionResponse")]
        string mDeleteMonthlyProjection(string strDeComID, string strMonthID, string strDivision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/gCheckProjectionActive", ReplyAction="http://tempuri.org/ISWPRJ/gCheckProjectionActiveResponse")]
        string gCheckProjectionActive(string strDeComID, string strDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetMontlyLadgerProjection", ReplyAction="http://tempuri.org/ISWPRJ/mGetMontlyLadgerProjectionResponse")]
        DPL.WEB.EXTRA.PCollectionCopmarison[] mGetMontlyLadgerProjection(string strDeComID, string strThisMonth, string strledger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetMontlyLadger", ReplyAction="http://tempuri.org/ISWPRJ/mGetMontlyLadgerResponse")]
        DPL.WEB.EXTRA.PCollectionCopmarison[] mGetMontlyLadger(string strDeComID, string strThisMonth, string strledger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetCollectionComparision", ReplyAction="http://tempuri.org/ISWPRJ/mGetCollectionComparisionResponse")]
        DPL.WEB.EXTRA.PCollectionCopmarison[] mGetCollectionComparision(string strDeComID, string strThisMonth, string strLastMont, string vstrUserName, int IntMode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetProjectionStarEndDate", ReplyAction="http://tempuri.org/ISWPRJ/mGetProjectionStarEndDateResponse")]
        DPL.WEB.EXTRA.PCollectionCopmarison[] mGetProjectionStarEndDate(string strDeComID, string strThisMonth, string strLastMont, string strProIndividual);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetCollectionComparisionReport", ReplyAction="http://tempuri.org/ISWPRJ/mGetCollectionComparisionReportResponse")]
        DPL.WEB.EXTRA.PCollectionCopmarison[] mGetCollectionComparisionReport(string strDeComID, string strProjectionName, string strFromMonthID, string strEndMonthID, int intmode, string strLedgerName, string strProjectionNamee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWPRJ/mGetProjectionReport", ReplyAction="http://tempuri.org/ISWPRJ/mGetProjectionReportResponse")]
        DPL.WEB.EXTRA.PCollectionCopmarison[] mGetProjectionReport(string strDeComID, string strProjectionName, string strFromMonthID, string strEndMonthID, int intmode, string strLedgerName, string strProjectionNamee);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWPRJChannel : DPL.WEB.EXTRA.ISWPRJ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWPRJClient : System.ServiceModel.ClientBase<DPL.WEB.EXTRA.ISWPRJ>, DPL.WEB.EXTRA.ISWPRJ {
        
        public SWPRJClient() {
        }
        
        public SWPRJClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWPRJClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWPRJClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWPRJClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayWeeklyProjectionchild(string strDeComID, string strMonthID, string strKey, string strLedgerName, string strProjection) {
            return base.Channel.mFillDisplayWeeklyProjectionchild(strDeComID, strMonthID, strKey, strLedgerName, strProjection);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayMonthlyProjectionchild(string strDeComID, string strMonthID, string strKey, string strLedgerName, string strProjection) {
            return base.Channel.mFillDisplayMonthlyProjectionchild(strDeComID, strMonthID, strKey, strLedgerName, strProjection);
        }
        
        public DPL.WEB.EXTRA.Mprojection[] mGetDivisionFromZone(string strDeComID, string strZone, int intHalt) {
            return base.Channel.mGetDivisionFromZone(strDeComID, strZone, intHalt);
        }
        
        public string mDeletePerformanve(string strcomId) {
            return base.Channel.mDeletePerformanve(strcomId);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mrptFillDisplayMonthlyProjection(string strDeComID, string strMonthID, string strDivision, int intmode) {
            return base.Channel.mrptFillDisplayMonthlyProjection(strDeComID, strMonthID, strDivision, intmode);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillWeeklyProjectionReport(string strDeComID, string strMonthID, string strDivision, int intmode) {
            return base.Channel.mFillWeeklyProjectionReport(strDeComID, strMonthID, strDivision, intmode);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillMonthlyProjectionValue(string strDeComID, string strMonthID, string strLedgerName, string strProjectionName) {
            return base.Channel.mFillMonthlyProjectionValue(strDeComID, strMonthID, strLedgerName, strProjectionName);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayLedgerNameWeeklyReport(string strDeComID, string strKey, string strDivision, int Intmode, string vstrUserName, string strZone) {
            return base.Channel.mFillDisplayLedgerNameWeeklyReport(strDeComID, strKey, strDivision, Intmode, vstrUserName, strZone);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillWeeklyProjectionList(string strDeComID, string VstruserName) {
            return base.Channel.mFillWeeklyProjectionList(strDeComID, VstruserName);
        }
        
        public string mDeleteWeeklyProjection(string strDeComID, string strMonthID) {
            return base.Channel.mDeleteWeeklyProjection(strDeComID, strMonthID);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayWeeklyProjection(string strDeComID, string strMonthID, string strDivision, string strMPO) {
            return base.Channel.mFillDisplayWeeklyProjection(strDeComID, strMonthID, strDivision, strMPO);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayLedgerNameWeekly(string strDeComID, string strKey, string strDivision) {
            return base.Channel.mFillDisplayLedgerNameWeekly(strDeComID, strKey, strDivision);
        }
        
        public string mInsertWeeklyProjectionSet(string strDeComID, string strKey, string strMonthID, string strDivision, string strBranchID, string strLedgerName, string strHeadName, double dblAmount, double dblWrittenAmount, int intDel, int intCols, int intRow, string strCommProjectionName) {
            return base.Channel.mInsertWeeklyProjectionSet(strDeComID, strKey, strMonthID, strDivision, strBranchID, strLedgerName, strHeadName, dblAmount, dblWrittenAmount, intDel, intCols, intRow, strCommProjectionName);
        }
        
        public DPL.WEB.EXTRA.ProjectonMonthConfig[] getZoneFromDivsion(string strDeComID, string strDivision) {
            return base.Channel.getZoneFromDivsion(strDeComID, strDivision);
        }
        
        public string mInsertMpoPerformance(string strDeComID, string strLedgerName, string strFdate, string strTdate, int intmode, int intSelection, int intbaseTarget, string strSelectionID, int intStatus) {
            return base.Channel.mInsertMpoPerformance(strDeComID, strLedgerName, strFdate, strTdate, intmode, intSelection, intbaseTarget, strSelectionID, intStatus);
        }
        
        public DPL.WEB.EXTRA.Mprojection[] mQueryPerformance(string strDeComID, int intMode) {
            return base.Channel.mQueryPerformance(strDeComID, intMode);
        }
        
        public DPL.WEB.EXTRA.Mprojection[] mGetLedgerGroupLoad(string strDeComID, int intMode, string struserName, int intstatus, string strBranchID) {
            return base.Channel.mGetLedgerGroupLoad(strDeComID, intMode, struserName, intstatus, strBranchID);
        }
        
        public string mInsertMonthConfig(string strDeComID, string strMonthID, string strMonthFromDate, string strMonthToDate, int intStatus) {
            return base.Channel.mInsertMonthConfig(strDeComID, strMonthID, strMonthFromDate, strMonthToDate, intStatus);
        }
        
        public DPL.WEB.EXTRA.ProjectonMonthConfig[] mFillMonthConfig(string strDeComID, int intStaus) {
            return base.Channel.mFillMonthConfig(strDeComID, intStaus);
        }
        
        public string DeletetMonthConfig(string strDeComID, int intSerialkey) {
            return base.Channel.DeletetMonthConfig(strDeComID, intSerialkey);
        }
        
        public string mUpdateMonthConfigpublic(string strDeComID, string strMonthID, string strFromDate, string strToDate, int intStatus, int intSerialKey) {
            return base.Channel.mUpdateMonthConfigpublic(strDeComID, strMonthID, strFromDate, strToDate, intStatus, intSerialKey);
        }
        
        public string mInsertProjectionSetup(string strDeComID, string strMonthID, string DgGrid) {
            return base.Channel.mInsertProjectionSetup(strDeComID, strMonthID, DgGrid);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillPojictionConfig(string strDeComID, string strMonthID) {
            return base.Channel.mFillPojictionConfig(strDeComID, strMonthID);
        }
        
        public string DeletetProjectionSetUp(string strDeComID, string strProjectionkey) {
            return base.Channel.DeletetProjectionSetUp(strDeComID, strProjectionkey);
        }
        
        public string mUpdateProjectionSetup(string strDeComID, string strMonthID, string DgGrid, string strProjectionKey) {
            return base.Channel.mUpdateProjectionSetup(strDeComID, strMonthID, DgGrid, strProjectionKey);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillMonthlyProjection(string strDeComID, string strProjectionMonth) {
            return base.Channel.mFillMonthlyProjection(strDeComID, strProjectionMonth);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillMonthlyProjectionLedger(string strDeComID, string strLedgerGroup, string strMonthID, int intmode) {
            return base.Channel.mFillMonthlyProjectionLedger(strDeComID, strLedgerGroup, strMonthID, intmode);
        }
        
        public string mInsertMonthlyProjection(string strDeComID, string strKey, string strMonthID, string strDivision, string strBranchID, string strLedgerName, string strHeadName, double dblAmount, int intDel, int intCols, int intRow) {
            return base.Channel.mInsertMonthlyProjection(strDeComID, strKey, strMonthID, strDivision, strBranchID, strLedgerName, strHeadName, dblAmount, intDel, intCols, intRow);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillMonthlyProjectionList(string strDeComID, string VstruserName) {
            return base.Channel.mFillMonthlyProjectionList(strDeComID, VstruserName);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayMonthlyProjection(string strDeComID, string strMonthID, string strDivision, string strprojectionKey) {
            return base.Channel.mFillDisplayMonthlyProjection(strDeComID, strMonthID, strDivision, strprojectionKey);
        }
        
        public DPL.WEB.EXTRA.ProjectionSet[] mFillDisplayLedgerName(string strDeComID, string strKey, string strDivision) {
            return base.Channel.mFillDisplayLedgerName(strDeComID, strKey, strDivision);
        }
        
        public string mDeleteMonthlyProjection(string strDeComID, string strMonthID, string strDivision) {
            return base.Channel.mDeleteMonthlyProjection(strDeComID, strMonthID, strDivision);
        }
        
        public string gCheckProjectionActive(string strDeComID, string strDate) {
            return base.Channel.gCheckProjectionActive(strDeComID, strDate);
        }
        
        public DPL.WEB.EXTRA.PCollectionCopmarison[] mGetMontlyLadgerProjection(string strDeComID, string strThisMonth, string strledger) {
            return base.Channel.mGetMontlyLadgerProjection(strDeComID, strThisMonth, strledger);
        }
        
        public DPL.WEB.EXTRA.PCollectionCopmarison[] mGetMontlyLadger(string strDeComID, string strThisMonth, string strledger) {
            return base.Channel.mGetMontlyLadger(strDeComID, strThisMonth, strledger);
        }
        
        public DPL.WEB.EXTRA.PCollectionCopmarison[] mGetCollectionComparision(string strDeComID, string strThisMonth, string strLastMont, string vstrUserName, int IntMode) {
            return base.Channel.mGetCollectionComparision(strDeComID, strThisMonth, strLastMont, vstrUserName, IntMode);
        }
        
        public DPL.WEB.EXTRA.PCollectionCopmarison[] mGetProjectionStarEndDate(string strDeComID, string strThisMonth, string strLastMont, string strProIndividual) {
            return base.Channel.mGetProjectionStarEndDate(strDeComID, strThisMonth, strLastMont, strProIndividual);
        }
        
        public DPL.WEB.EXTRA.PCollectionCopmarison[] mGetCollectionComparisionReport(string strDeComID, string strProjectionName, string strFromMonthID, string strEndMonthID, int intmode, string strLedgerName, string strProjectionNamee) {
            return base.Channel.mGetCollectionComparisionReport(strDeComID, strProjectionName, strFromMonthID, strEndMonthID, intmode, strLedgerName, strProjectionNamee);
        }
        
        public DPL.WEB.EXTRA.PCollectionCopmarison[] mGetProjectionReport(string strDeComID, string strProjectionName, string strFromMonthID, string strEndMonthID, int intmode, string strLedgerName, string strProjectionNamee) {
            return base.Channel.mGetProjectionReport(strDeComID, strProjectionName, strFromMonthID, strEndMonthID, intmode, strLedgerName, strProjectionNamee);
        }
    }
}
